name: Create Jira Ticket and Link

on:
  issues:
    types: [opened]

jobs:
  create-and-link-jira-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Jira Issue
        id: create-jira
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        run: |
          RESPONSE=$(curl -s -w "%{http_code}" -o response.json -X POST \
          "$JIRA_BASE_URL/rest/api/3/issue/" \
          -u $JIRA_USER_EMAIL:$JIRA_API_TOKEN \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{
                "fields": {
                   "project": {
                     "key": "KAN"
                   },
                   "summary": "${{ github.event.issue.title }}",
                   "description": {
                     "type": "doc",
                     "version": 1,
                     "content": [
                       {
                         "type": "paragraph",
                         "content": [
                           {
                             "text": "${{ github.event.issue.body }}",
                             "type": "text"
                           }
                         ]
                       }
                     ]
                   },
                   "issuetype": {
                     "name": "Task"
                   }
                 }
              }')
          if [ $(echo $RESPONSE | tail -n1) != "201" ]; then
            echo "Failed to create Jira issue"
            cat response.json
            exit 1
          fi
          
          JIRA_KEY=$(jq -r .key response.json)
          echo "::set-output name=jira_key::$JIRA_KEY"
          echo "Jira issue $JIRA_KEY created successfully."

      - name: Update GitHub Issue with Jira Key
        if: steps.create-jira.outputs.jira_key
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue has been linked to a Jira ticket: ${{ steps.create-jira.outputs.jira_key }}
