name: Sync Issue Status with Jira

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  update-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Fetch issue comments and save to file
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments" > comments.json

      - name: Install Python dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          # If your script depends on other packages, install them here
          # pip install requests

      - name: Extract Jira issue key using Python
        run: |
          JIRA_KEY=$(python extract_jira_key.py < comments.json)
          echo "Extracted JIRA_KEY: $JIRA_KEY"
          if [[ -z "$JIRA_KEY" ]]; then
            echo "No Jira key found"
            exit 1
          else
            echo "JIRA_KEY=$JIRA_KEY" >> $GITHUB_ENV
          fi

      - name: Check if label is 'Done'
        if: contains(github.event.issue.labels.*.name, 'Done')
        run: |
          echo "Label 'Done' found. Preparing to update Jira issue status."
          TRANSITION_ID="31" # Adjust with your actual ID for 'Done' status
          echo "TRANSITION_ID=$TRANSITION_ID" >> $GITHUB_ENV

      - name: Update Jira issue status to 'Done'
        if: env.JIRA_KEY && env.TRANSITION_ID
        run: |
          echo "Updating Jira issue $JIRA_KEY to 'Done' status using Transition ID $TRANSITION_ID"
          curl -X POST \
            --url "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/$JIRA_KEY/transitions" \
            --header 'Content-Type: application/json' \
            --user "${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            --data '{"transition":{"id":"'"$TRANSITION_ID"'"}}'
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
